blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/ePaysa-ind/askChinna/discussions
    about: Please ask and answer questions here.
  - name: Email Support
    url: mailto:admin@epaysa.com
    about: Contact us directly for sensitive issues